### ISSUE TITLE
Stable release tag?

### ISSUE THREAD

**Issue by phptek** [elliot-sawyer/silverstripe-mysql-ssl#2]
Can you create a stable release tag e.g. 0.0.2 please? Just so we don't need to refer to a somewhat transient branch-name in `composer.json`. Ta

**Comment by elliot-sawyer** [comment]
I think I was holding off on 0.0.2 because of Azure support, but the extra commit is just some docs. I'll tag shortly

**Comment by elliot-sawyer** [comment]
done

**Comment by elliot-sawyer** [comment]
Merged and tagged 1.0.0
