### ISSUE TITLE
test with mysqlnd_azure

### ISSUE THREAD

**Issue by tractorcow** [elliot-sawyer/silverstripe-mysql-ssl#4]
Hiya, has this module been tested with https://github.com/microsoft/mysqlnd_azure? I'm about to try it out.

**Comment by elliot-sawyer** [comment]
I have tested MySQL running on an Azure environment, but not with that module. There's a feature branch with setup instructions here, more feedback and validation would be useful!  https://github.com/elliot-sawyer/silverstripe-mysql-ssl/tree/feature/azure

**Comment by tractorcow** [comment]
Protip; it works well :)

I've been running that azure branch, thanks @elliot-sawyer :)

The azure docs say to use the new CA certificate; I found that the new one doesn't work, so I stuck with BaltimoreCyberTrustRoot.crt.pem 

That ate up more time in my afternoon than I really wanted !

@elliot-sawyer I think this could probably go back up to core; It's good work and solves a lot of problems. :)

Good trick with the null catch; It basically solves null configs the same way that laravel does, so you can distinguish between null / empty strings. I wish we had defined these a bit earlier in 4.0 beta.
